### ISSUE TITLE
Can you give me a demo?

### ISSUE THREAD

**Issue by white-hy** [dykuang/Medical-image-registration#1]
Hello, I am very lucky to see your research.If I only want to register a pair of 3D images, which script should I run?

**Comment by dykuang** [comment]
Sorry for the late reply. You can modify `eval.py` to suit your needs ignoring all the lines uses label information. 

Preprocess of your image are needed. In the code, the resolution is 144 by 180 by 144, and each image volume is normalized by its max intensity. 

You also need to change the interpolation method from ''nearest" to "linear"  in the line of "warp_seg"
`warp_seg = interpn((yy, xx, zz), brain_test_1, sample, method='linear', bounds_error=False, fill_value=0)`

**Comment by white-hy** [comment]
Thanks a lot
