### ISSUE TITLE
About the grid visualisation

### ISSUE THREAD

**Issue by yangglebin** [dykuang/Medical-image-registration#12]
Hello, dykuang:

I'm implementing your vis_grid function in visual.py, The registration field I used is (31,31,3), 
and i use the command line  vis_grid(flow[:, :, ::2], res=1, direct=2),after that, i got a likely wrong result. The result is:
      [444](https://user-images.githubusercontent.com/26767902/83387689-bd97b900-a41f-11ea-8022-b42c9a0cf533.png)

**Comment by dykuang** [comment]
Hello,
          Did you mean the displacement field used is of size (31,31,31,3)? Since the code example is for viewing a slice projection for 3D images. As an example, if the first three dimensions are arranged as [x,y,z], the three channels of the displacement field is also stacked as [x,y,z] and you would like to visualize for xy plane at the 16th slice along z-axis, you would do  `vis_grid(flow[:, :, 15,  :2], res=1, direct=2)`. If you would like to visualize projections for xz plane at the 10th slice along y-axis, you would do  `vis_grid(flow[:, 9, :, ::2], res=1, direct=2)`.  For this, you may want to double check your images's coordinates' orientation. It may be helpful by putting the corresponding image slice along with the warped grid by the side to check the consistency.
    It is also possible that the displacement field learned is not smooth. You can try multiple the field with a small scalar or simply zero and then pass it to the `vis_grid` function for further investigation into the problem. The function should give you the regular grid if zero displacement is passed as input.
