### ISSUE TITLE
how to train the model using my own images?

### ISSUE THREAD

**Issue by dzz416** [dykuang/Medical-image-registration#14]

**Comment by dykuang** [comment]
You can check the `train.py` inside source folder. 

First, Depending on your image size, you need to change the dictionary `par` to suit your images' actually size, or resize your image to the default size. Usually sizes as powers of 2 will cause no problem. If you encounter errors about tensor sizes when compiling the model , you may also need to change the padding inside the network. 

Second, you can modify `vol_generator` function to feed the image pairs to the network as your need. In my experiment, both source(moving) and target(fixed) images are saved in the same folder as `.npy`.  I load them according to different
combinations and stacked them as the input (check line 70-74).

Last, the code was written with tf1.x, you may need to make other necessary modifications if you are using tf2.x.
