### ISSUE TITLE
3D displacement

### ISSUE THREAD

**Issue by dongdongliao** [dykuang/Medical-image-registration#2]
Hello, may I ask whether the pixel value of some blocks of the image is 0 after the displacement occurs in the process of debugging the code?Thank you very much!

**Comment by dykuang** [comment]
Sorry for the late reply.

If you could send me a piece of your code or an example, it will help me diagnose. For now it could be many reasons such as improper preprocess of images, model is under trained or simply a mistake in the implementation.
