### ISSUE TITLE
about 'Get_Jac()'

### ISSUE THREAD

**Issue by white-hy** [dykuang/Medical-image-registration#3]
Hi,Dear Author,Your code has helped me a lot.
I noticed that the 'Get_Jac()' in  'Utils.py'  appaers '+1'. So...what does this '+1' do.
Just like this picture
![image](https://user-images.githubusercontent.com/33248778/60569209-57369080-9da1-11e9-8f4a-42dff110f85e.png)

**Comment by dykuang** [comment]
Hello,

        Because displacement u is used to approximate the deformation f, i.e f = Id + u. So when Jacobian is calculated, it should be Df = Id + Du, where Id is the identity matrix. 1 in the code is when adding the 1 from this identity matrix.

**Comment by white-hy** [comment]
By visualizing the det of the jacobian matrix for each pixel，I got the following result.
![image](https://user-images.githubusercontent.com/33248778/60677717-dff22100-9eb4-11e9-9920-d9432e91fb66.png)
Does the red part represent the position of the negative jacobians?Does that mean the red part is folded?

**Comment by white-hy** [comment]
Hi,Dear Author
By visualizing the det of the jacobian matrix for each pixel，I got the following result.
![image](https://user-images.githubusercontent.com/33248778/60677937-7aeafb00-9eb5-11e9-8200-f010b763082b.png)
Does the red part represent the position of the negative jacobians?Does that mean the red part is folded?
Looking forward to your reply!

**Comment by dykuang** [comment]
Hello,
       The visualization will depend on what colormap you are using. If you used `matplotlib.pyplot` package and set `colormap=bwr`, the midpoint by default to normalize the colormap is 1. In this case, red locations means expansion. If you want to check negative jacobian determinant locations, you should normalize your data with midpoint=0 (you can use the `MidpointNormalize` function in `visual.py`)and set  `colormap=bwr_r`.  As a example, try something like `plt.imshow(your_data, cmap='bwr_r', norm = MidpointNormalize(midpoint=0))`
       Another thing to be careful is your coordinate system, the `Get_Ja()` function I used is with a special coordinate of my data. If your image data is in different coordinate/orientation, you should modify the code. For example,  change the first line to `Dx = ...` instead of `Dy = ...` in the original code.

**Comment by white-hy** [comment]
Hi,Dear Author
I am very sorry for my late reply.
I did exactly what you said .I set `plt.imshow(your_data, cmap='bwr_r', norm = MidpointNormalize(midpoint=0))` and I chose coordinate system that fit my data . Then, I got this result.
![image](https://user-images.githubusercontent.com/33248778/60793388-3784db00-a19a-11e9-9bfd-34fe2b05f333.png)
What do the red and blue location in the figure mean? Does the red position represent negative jacobian? So what about the blue position?

**Comment by white-hy** [comment]
Hi,Dear Author
I am very sorry for my late reply.
I did exactly what you said .I set `plt.imshow(your_data, cmap='bwr_r', norm = MidpointNormalize(midpoint=0))` and I chose coordinate system that fit my data . Then, I got this result.
![](https://user-images.githubusercontent.com/33248778/60793388-3784db00-a19a-11e9-9bfd-34fe2b05f333.png)
What do the red and blue location in the figure mean? Does the red location represent negative jacobian? So what about the blue location ?

**Comment by dykuang** [comment]
If calculation is done properly. Yes, red locations are locations of foldings and blue locations are where the jacobian determinant are non-negative. To reduce folding locations, you can use a anti-folding loss, train the data with a cycle-consistent way (you can check the two arxiv paper drafts in this repository) or uses a architecture as in the paper of ``Unsupervised Learning of Probabilistic Diffeomorphic Registration for Images and Surfaces".

**Comment by white-hy** [comment]
Thank you very much for your help. I will try the way you said right away.
