### ISSUE TITLE
Grid visualization 

### ISSUE THREAD

**Issue by hfahad** [dykuang/Medical-image-registration#4]
Hello,
i need to ask one question. can you please tell me which function you use for visualization of grid.
That you show in folding effect grid 
https://github.com/dykuang/Medical-image-registration/blob/master/CheckJac_short.png
shown in this pic
Kind regards
Hafiz

**Comment by dykuang** [comment]
Hello hfahad,
       Sorry for replying late. I used `vis_grid()` function in the `visual.py` script. It takes a 2D displacements as input. For example, I used `vis_grid(deformation[72,:,:,::2])` where deformation is the displacements predicted by the network. You need to be careful about the the coordinate combination (i.e. XY, XZ or YZ) you choose to view the projection.

**Comment by white-hy** [comment]
@dykuang Hi !  Dear Author,great Work!
I am using `vis_grid()` to visualize my deformation field! When I using this function, do I need to normalize the deformation field to (-1,1) or (0,1)?

**Comment by dykuang** [comment]
@white-hy No, I don't think so since the grid used in the 3D deformer module is the regular grid instead of rescaled grid.

**Comment by white-hy** [comment]
@dykuang Sorry, I am a bit confused about the rescaled grid. Can you explain it briefly?

**Comment by dykuang** [comment]
@white-hy If you check the `_meshgrid` method of class `SpatialDeformer3D` in `spatial_deformer_net3d.py`, you will find that the current implementation uses the regular grid (that is every voxel location is indexed by 3 integers: 0 to width-1, 0 to height-1 and 0 to  depth -1 ). This meshed grid + displacements predicted results in a transformed grid that will be used in `interpolation` method to do a trilinear interpolation of the source image. If you prefer a rescaled grid, you can modified the 3 lines starting with `tf.linspace` and add codes for the proper rescaling of the transformed grid in `_interpolate` method. You may also need to attention on the activation function of your last layer producing the displacements to control the scale of your output for a better training. Hope this answers your question.

**Comment by white-hy** [comment]
@dykuang Thank you for your detailed explanation, I will do what you said. I will try to read your code carefully to figure out how it works.
Thanks again
