### ISSUE TITLE
Calculation of Jacobian

### ISSUE THREAD

**Issue by riccardosamperna** [dykuang/Medical-image-registration#5]
Dear @dykuang,
first of all thanks a lot for sharing your code. 
I read the two papers in arxiv and I am interested in the problem of the negative Jacobian in the deformation field. Looking at your code I did not really understand the way you calculate the Jacobian and the related function Get_Ja(). Can you please explain me how you 

> Calculate the Jacobian value at each point of the displacement map

**Comment by dykuang** [comment]
Hello Riccardo,
            Here is what I did. Let's say the displacement is u(x, y, z) = <u_1, u_2, u_3>, where u1, u2, u3 are stacked in the last channel of the predicted displacements. The first 3 lines in the function are just calculating the space differential using first order finite difference (We only need the qualitative behaviors here, so this simple scheme will suffice). If you are wondering why `Dy` comes first, that is because my "weird" coordinates used in `spatial_deformernet_3d.py`. You can modify them to suite your coordinates. The determinant is then calculated by expanding the Jacobian matrix according to its first column.
             Because displacement u is used to approximate the deformation f, i.e f(x) = x + u(x). So when Jacobian is calculated, it should be Df = Id + Du, where Id is the identity matrix. 1 in the code is when adding the 1 from this identity matrix.  Hope this answers your question.

**Comment by riccardosamperna** [comment]
Thank you for the clear explanation @dykuang.
