### ISSUE TITLE
save checkpoints

### ISSUE THREAD

**Issue by farhanone** [dykuang/Medical-image-registration#6]
Thanks for the code.

I am trying to save the checkpoints after every epoch by the following.
```
from keras.callbacks import ModelCheckpoint
mc = ModelCheckpoint(outpath+'SDN3d_weights_TVS16_{epoch:02d}.ckpt', save_weights_only=True, verbose=1, period=1)
history = sdn.fit_generator(gen_train, steps_per_epoch=2, callbacks=[mc], epochs=2, verbose=1, validation_data=gen_test, validation_steps=len(f_img_v)/batch_size)
```
the above code generates the checkpoints file but when I try to load them in the eval.py by `sdn.load_weights(r'path_to_file')`, there is error 

> "ValueError: You are trying to load a weight file containing 2 layers into a model with 18 layers."

Thanks in advance

**Comment by dykuang** [comment]
Hello,
         Sorry for the late reply. In the training process, the weights you saved for `sdn` are of 2 layers:
the weights for the displacement network (the one produces displacement field) and the layer (actually no weights here, but the operations exist for this layer) for the interpolation to produce warped image. While in the `eval.py`, only the displacement network is used (still named as `sdn` but *different*. it is only the first layer of model you trained. )
          To load the weights correctly, either you modify your callback so that it only saves the weights of the displacement network, or you can rebuild the whole model as in training and then the `load_weights` function should work fine.

**Comment by farhanone** [comment]
Thanks.
