### ISSUE TITLE
why jacobian determinant can be computed like this way? 

### ISSUE THREAD

**Issue by qixiaomu77** [dykuang/Medical-image-registration#8]
It's like a math question,I thought a lot but can't find the answer.

def Get_Ja(displacement):

    '''
    Calculate the Jacobian value at each point of the displacement map having

    size of b*h*w*d*3 and in the cubic volumn of [-1, 1]^3

    '''

    D_y = (displacement[:,1:,:-1,:-1,:] - displacement[:,:-1,:-1,:-1,:])

    D_x = (displacement[:,:-1,1:,:-1,:] - displacement[:,:-1,:-1,:-1,:])

    D_z = (displacement[:,:-1,:-1,1:,:] - displacement[:,:-1,:-1,:-1,:])

    D1 = (D_x[...,0]+1)*( (D_y[...,1]+1)*(D_z[...,2]+1) - D_z[...,1]*D_y[...,2])

    D2 = (D_x[...,1])*(D_y[...,0]*(D_z[...,2]+1) - D_y[...,2]*D_x[...,0])

    D3 = (D_x[...,2])*(D_y[...,0]*D_z[...,1] - (D_y[...,1]+1)*D_z[...,0])

    return D1-D2+D3

**Comment by junyuchen245** [comment]
From my understa

> It's like a math question,I thought a lot but can't find the answer.
> 
> def Get_Ja(displacement):
> 
> ```
> '''
> Calculate the Jacobian value at each point of the displacement map having
> 
> size of b*h*w*d*3 and in the cubic volumn of [-1, 1]^3
> 
> '''
> 
> D_y = (displacement[:,1:,:-1,:-1,:] - displacement[:,:-1,:-1,:-1,:])
> 
> D_x = (displacement[:,:-1,1:,:-1,:] - displacement[:,:-1,:-1,:-1,:])
> 
> D_z = (displacement[:,:-1,:-1,1:,:] - displacement[:,:-1,:-1,:-1,:])
> 
> 
> 
> D1 = (D_x[...,0]+1)*( (D_y[...,1]+1)*(D_z[...,2]+1) - D_z[...,1]*D_y[...,2])
> 
> D2 = (D_x[...,1])*(D_y[...,0]*(D_z[...,2]+1) - D_y[...,2]*D_x[...,0])
> 
> D3 = (D_x[...,2])*(D_y[...,0]*D_z[...,1] - (D_y[...,1]+1)*D_z[...,0])
> 
> return D1-D2+D3
> ```

Hi,

From my understanding, Dy, Dx, and Dz are the forward approximations used to approximate Jacobian matrixes. But since these are displacements (u), and phi = id + u. An identity matrix has to be added in order to get phi (that's what the plus 1s means, I think...). D1 - D2 + D3 is simply the calculation of the determinant of a 3x3 matrix. 

Junyu

**Comment by MangoWAY** [comment]
> > It's like a math question,I thought a lot but can't find the answer.
> > def Get_Ja(displacement):
> > ```
> > '''
> > Calculate the Jacobian value at each point of the displacement map having
> > 
> > size of b*h*w*d*3 and in the cubic volumn of [-1, 1]^3
> > 
> > '''
> > 
> > D_y = (displacement[:,1:,:-1,:-1,:] - displacement[:,:-1,:-1,:-1,:])
> > 
> > D_x = (displacement[:,:-1,1:,:-1,:] - displacement[:,:-1,:-1,:-1,:])
> > 
> > D_z = (displacement[:,:-1,:-1,1:,:] - displacement[:,:-1,:-1,:-1,:])
> > 
> > 
> > 
> > D1 = (D_x[...,0]+1)*( (D_y[...,1]+1)*(D_z[...,2]+1) - D_z[...,1]*D_y[...,2])
> > 
> > D2 = (D_x[...,1])*(D_y[...,0]*(D_z[...,2]+1) - D_y[...,2]*D_x[...,0])
> > 
> > D3 = (D_x[...,2])*(D_y[...,0]*D_z[...,1] - (D_y[...,1]+1)*D_z[...,0])
> > 
> > return D1-D2+D3
> > ```
> 
> Hi,
> 
> From my understanding, Dy, Dx, and Dz are the forward approximations used to approximate Jacobian matrixes. But since these are displacements (u), and phi = id + u. An identity matrix has to be added in order to get phi (that's what the plus 1s means, I think...). D1 - D2 + D3 is simply the calculation of the determinant of a 3x3 matrix.
> 
> Junyu

Maybe the D2 should be (D_x[...,1])*(D_y[...,0]*(D_z[...,2]+1) - D_y[...,2]*D_z[...,0])

**Comment by dykuang** [comment]
@MangoWAY . Yes, you are right. Thanks for pointing out this typo. It is now updated.
