### ISSUE TITLE
How to preprocess the data?

### ISSUE THREAD

**Issue by RitchieAlpha** [dykuang/Medical-image-registration#9]
Dear dykuang,
This repository helps me a lot, but there is something confused me a lot. The question is how to preprocess the data? Can you explain this to me? 
Thanks

**Comment by dykuang** [comment]
There could be multiple way for preprocess. For the two papers mentioned in README, we just took one of the easiest approach to normalize the voxel intensity to [0,1]: given each volume A, we divide by its maximum voxel value, i.e. A <- A/max(A).  Feel free to try other preprocesses, they may provide better results.
